import {Injectable, Inject, Component, Directive, InjectionToken, Type} from "@angular/core";
//import {TRANSLATION_PROVIDERS, TRANSLATIONS} from "./translations";

export const TRANSLATIONS = new InjectionToken<any>('translations', {
  providedIn: 'root',
  factory: () => sessionStorage
});
export const LANG_ENG_NAME = 'eng';
export const LANG_ENG_TRANS = {
  "Example"                                                            :   "Example",
  "must be a well-formed email address"                                :   "must be a well-formed email address",
  "Error: A registry process should be made!"                          :   "A registry process should be made!",
  "Error: A registry process un valid!"                                :   "Incorrect user name",
  "VALIDATION_FAILED"                                                  :   "A registry process un valid!",
  "Bad credentials"                                                    :   "Incorrect user name or password",
  "Password matches one of %1$s previous passwords."                   :   "Try again with a password you haven`t used before",
  "Passwords do not match!"                                            :   "Passwords do not match!",
  "Error: Email is already in use!"                                    :   "Email is already in use!",
  "Error: Invalidate Pin-Code! User Not Approved"                      :   "The Verification Code does not match",
  "Error: Unable to save your changes"                                 :   "Unable to save your changes",
  "User account is locked"                                             :   "Your account has been locked",
  "Details Saved"                                                      :   "Your account has been locked",

  "3 Days to expire"                                                   :   "3 Days to expire",
  "A minimum of 8 characters"                                          :   "A minimum of 8 characters",
  "At least 1 Uppercase letters"                                       :   "At least 1 Uppercase letters",
  "At least 1 Lowercase letters"                                       :   "At least 1 Lowercase letters",
  "A number"                                                           :   "A number",
  "APP CENTER"                                                         :   "APP CENTER",
  "Admin"                                                              :   "Admin",
  "Aeonix App Center"                                                  :   "Aeonix App Center",
  "Agent"                                                              :   "Agent",
  "CHANGE PASSWORD"                                                    :   "CHANGE PASSWORD",
  "Change Password"                                                    :   "Change Password",
  "Change Password and Login"                                          :   "Change Password and Login",
  "Change it now >"                                                    :   "Change it now >",
  "Change the Initial Password"                                        :   "Change the Initial Password",
  "Chinese"                                                            :   "Chinese",
  "Complete Registration"                                              :   "Complete Registration",
  "Continue"                                                           :   "Continue",
  "EMAIL"                                                              :   "Email",
  "Enable Profile Picture"                                             :   "Enable Profile Picture",
  "English"                                                            :   "English",
  "Ex. Saul Ramirez"                                                   :   "Ex. Saul Ramirez",
  "Ex: +972547762084"                                                  :   "Ex: +972547762084",
  "Ex: abc@example.com"                                                 :   "Ex: abc@example.com",
  "FORGOT PASSWORD"                                                    :   "FORGOT PASSWORD",
  "Forgot Password?"                                                   :   "Forgot Password?",
  "Script-Designer"                                                    :   "Script Designer",
  "Hebrew"                                                             :   "Hebrew",
  "INITIAL PASSWORD"                                                   :   "password",
  "LOGIN SCREEN"                                                       :   "LOGIN SCREEN",
  "Log out"                                                            :   "Log out",
  "Login"                                                              :   "Login",
  "My Account"                                                         :   "My Account",
  "NEW PASSWORD"                                                       :   "NEW Password",
  "OLD PASSWORD"                                                       :   "OLD PASSWORD",
  "PASSWORD"                                                           :   "Password",
  "Please enter the Verification Code"                                 :   "Please enter the Verification Code",
  "you received in your mail:"                                         :   "you received in your mail:",
  "Please enter your User Name:"                                       :   "Please enter your User Name:",
  "Send Verification Code again"                                       :   "Send Verification Code again",
  "REGISTRATION"                                                       :   "REGISTRATION",
  "Russian"                                                            :   "Russian",
  "Send me a Verification Code"                                        :   "Send me a Verification Code",
  "Spanish"                                                            :   "Spanish",
  "The password must contain:"                                         :   "The password must contain:",
  "USER DETAILS"                                                       :   "USER DETAILS",
  "USER NAME"                                                          :   "USERNAME",
  "WebRT"                                                              :   "WebRT",
  "You have successfully changed your password!"                       :   "You have successfully changed your password!",
  "You have successfully completed your registration!"                 :   "You have successfully completed your registration!",
  "Your password has expired and must be changed"                      :   "Your password has expired and must be changed",
  "Your password will expire in "                                      :   "Your password will expire in ",
  " Days."                                                             :   " Days.",
  "Complete the registration by filling the missing info:"             :   "Complete the registration by filling the missing info:",
  "PHONE NUMBER FOR AUTHENTICATION"                                    :   "PHONE NUMBER FOR AUTHENTICATION",
  "RE-ENTER NEW PASSWORD"                                              :   "re-enter new Password",
  "resend the verification code"                                       :   "resend the verification code",
  "Strength : "                                                        :   "Strength : ",
  "Must contain phone:"                                                :   "Must contain phone:",
  "A well-formed phone number"                                         :   "A well-formed phone number",
  "Must contain email:"                                                :   "Must contain email:",
  "A well-formed email address"                                        :   "A well-formed email address",

};
export const LANG_CHI_NAME = 'chi';
export const LANG_CHI_TRANS = {
  "Example"                                                            :   "例如",
  "must be a well-formed email address"                                :   "请输入正确的邮箱地址",
  "Error: A registry process should be made!"                          :   "应该先完成注册！",
  "Error: A registry process un valid!"                                :   "用户名有误",
  "VALIDATION_FAILED"                                                  :   "注册无效！",
  "Bad credentials"                                                    :   "用户名或密码有误",
  "Password matches one of %1$s previous passwords."                   :   "请用一个以前没用过的密码再试一次",
  "Passwords do not match!"                                            :   "密码不符！",
  "Error: Email is already in use!"                                    :   "此邮箱已被使用！",
  "Error: Invalidate Pin-Code! User Not Approved"                      :   "验证码不符",
  "Error: Unable to save your changes"                                 :   "无法保存修改的内容",
  "User account is locked"                                             :   "您的账号已被锁定",
  "Details Saved"                                                      :   "您的账号已被锁定",

  "3 Days to expire"                                                   :   "三天后到期",
  " A minimum of 8 characters"                                          :   "至少包含8个字符",
  " At least 1 Uppercase letters"                                      :   "至少包含1个大写字母",
  " At least 1 lowercase letters"                                      :   "至少包含1个小写字母",
  " At least 1 special character"                                      :   "至少包含1个特殊字符",
  " A number"                                                           :   "一个数字",
  "APP CENTER"                                                         :   "应用中心",
  "Admin"                                                              :   "管理员",
  "Aeonix App Center"                                                  :   "Aeonix 应用中心",
  "Agent"                                                              :   "坐席",
  "CHANGE PASSWORD"                                                    :   "修改密码",
  "Change Password"                                                    :   "修改密码",
  "Change Password and Login"                                          :   "修改密码然后登录",
  "Change it now >"                                                    :   "立即修改>",
  "Change the Initial Password"                                        :   "修改初始密码",
  "Chinese"                                                            :   "中文",
  "Complete Registration"                                              :   "完成注册",
  "Continue"                                                           :   "继续",
  "EMAIL"                                                              :   "电子邮件",
  "Enable Profile Picture"                                             :   "使用个人资料图片",
  "English"                                                            :   "英语",
  "Ex. Saul Ramirez"                                                   :   "例如：Saul Ramirez",
  "Ex: +972547762084"                                                  :   "例如：+972547762084",
  "Ex: abc@example.com"                                                :   "例如：abc@example.com",
  "FORGOT PASSWORD"                                                    :   "忘记密码",
  "Forgot Password?"                                                   :   "忘记密码？",
  "Script-Designer"                                                    :   "脚本设计器",
  "Hebrew"                                                             :   "希伯来语",
  "INITIAL PASSWORD"                                                   :   "初始密码",
  "LOGIN SCREEN"                                                       :   "登录界面",
  "Log out"                                                            :   "注销",
  "Login"                                                              :   "登录",
  "My Account"                                                         :   "我的账户",
  "NEW PASSWORD"                                                       :   "新密码",
  "OLD PASSWORD"                                                       :   "旧密码",
  "PASSWORD"                                                           :   "密码",
  "Please enter the Verification Code"                                 :   "请输入验证码",
  "you received in your mail:"                                         :   "你在邮件中收到的：",
  "Please enter your User Name:"                                       :   "请输入你的用户名：",
  "Send Verification Code again"                                       :   "再次发送验证码",
  "REGISTRATION"                                                       :   "注册",
  "Russian"                                                            :   "俄语",
  "Send me a Verification Code"                                        :   "给我发送验证码",
  "Spanish"                                                            :   "西班牙语",
  "The password must contain:"                                         :   "密码必须包含：",
  "USER DETAILS"                                                       :   "用户信息",
  "USER NAME"                                                          :   "用户名",
  "WebRT"                                                              :   "WebRT",
  "You have successfully changed your password!"                       :   "您已成功修改密码！",
  "You have successfully completed your registration!"                 :   "您已成功完成注册！",
  "Your password has expired and must be changed"                      :   "您的密码已过期，必须修改",
  "Your password will expire in "                                      :   "您的密码将在",
  " Days."                                                             :   "天后过期。",
  "Complete the registration by filling the missing info:"             :   "通过填写以下信息完成注册：",
  "PHONE NUMBER FOR AUTHENTICATION"                                    :   "输入电话号码进行验证",
  "RE-ENTER NEW PASSWORD"                                              :   "重新输入新密码",
  "resend the verification code"                                       :   "重新发送验证码",
  "Strength : "                                                        :   "强度 : ",
  "Must contain phone:"                                                :   "必须包含电话：",
  "A well-formed phone number"                                         :   "一个正确的电话号码",
  "Must contain email:"                                                :   "必须包含电邮地址：",
  "A well-formed email address"                                        :   "一个正确的电子邮件地址",
};
export const LANG_ESP_NAME = 'esp';
export const LANG_ESP_TRANS = {
    "Example"                                                            :   "Ejemplo",
    "must be a well-formed email address"                                :   "debe ser una dirección de correo electrónica bien formada",
    "Error: A registry process should be made!"                          :   "¡Se debe completar un proceso de registro!",
    "Error: A registry process un valid!"                                :   "Nombre de usuario incorrecto",
    "VALIDATION_FAILED"                                                  :   "¡El proceso de registro no válido!",
    "Bad credentials"                                                    :   "Usuario o contraseña incorrecta",
    "Password matches one of %1$s previous passwords."                   :   "Vuelve a intentarlo con una contraseña que no hayas usado antes",
    "Passwords do not match!"                                            :   "¡Las contraseñas no coinciden!",
    "Error: Email is already in use!"                                    :   "¡Correo electrónico ya está en uso!",
    "Error: Invalidate Pin-Code! User Not Approved"                      :   "El código de verificación no coincide",
    "Error: Unable to save your changes"                                 :   "No se pueden guardar los cambios",
    "User account is locked"                                             :   "Su cuenta ha sido bloqueada",
    "Details Saved"                                                      :   "Su cuenta ha sido bloqueada",

    "3 Days to expire"                                                   :   "Expira en 3 días",
    " A minimum of 8 characters"                                         :   "Un mínimo de 8 caracteres",
    " At least 1 Uppercase letters"                                      :   "Al menos 1 letras mayúsculas",
    " At least 1 lowercase letters"                                      :   "Al menos 1 letras minúsculas",
    " At least 1 special character"                                      :   "Al menos 1 letras minúsculas",
    " A number"                                                          :   "Un número",
    "APP CENTER"                                                         :   "CENTRO DE APLICACIONES",
    "Admin"                                                              :   "Administrador",
    "Aeonix App Center"                                                  :   "Centro de aplicaciones Aeonix",
    "Agent"                                                              :   "Agente",
    "CHANGE PASSWORD"                                                    :   "CAMBIAR LA CONTRASEÑA",
    "Change Password"                                                    :   "Cambiar la contraseña",
    "Change Password and Login"                                          :   "Cambiar contraseña e iniciar sesión",
    "Change it now >"                                                    :   "Cámbialo ahora >",
    "Change the Initial Password"                                        :   "Cambiar la contraseña inicial",
    "Chinese"                                                            :   "Chino",
    "Complete Registration"                                              :   "Registracion completa",
    "Continue"                                                           :   "Continuar",
    "EMAIL"                                                              :   "Correo electrónico",
    "Enable Profile Picture"                                             :   "Habilitar imagen de perfil",
    "English"                                                            :   "Inglés",
    "Ex. Saul Ramirez"                                                   :   "Ej. Saúl Ramírez",
    "Ex: +972547762084"                                                  :   "Ej: +972547762084",
    "Ex: abc@example.com"                                                :   "Ej: abc@ejemplo.com",
    "FORGOT PASSWORD"                                                    :   "HAS OLVIDADO TU CONTRASEÑA",
    "Forgot Password?"                                                   :   "¿Has olvidado tu contraseña?",
    "Script-Designer"                                                    :   "Diseñador de guiones",
    "Hebrew"                                                             :   "Hebreo",
    "INITIAL PASSWORD"                                                   :   "Contraseña inicial",
    "LOGIN SCREEN"                                                       :   "PANTALLA DE INGRESO AL SISTEMA",
    "Log out"                                                            :   "Cerrar sesión",
    "Login"                                                              :   "Iniciar sesión",
    "My Account"                                                         :   "Mi cuenta",
    "NEW PASSWORD"                                                       :   "Nueva contraseña",
    "OLD PASSWORD"                                                       :   "CONTRASEÑA ANTERIOR",
    "PASSWORD"                                                           :   "Contraseña",
    "Please enter the Verification Code"                                 :   "Porfavor ingrese el codigo de verificacion",
    "you received in your mail:"                                         :   "Lo recibiste en tu correo:",
    "Please enter your User Name:"                                       :   "Por favor, ingrese su usuario:",
    "Send Verification Code again"                                       :   "Enviar código de verificación de nuevo",
    "REGISTRATION"                                                       :   "REGISTRACION",
    "Russian"                                                            :   "Ruso",
    "Send me a Verification Code"                                        :   "Envíame un código de verificación",
    "Spanish"                                                            :   "Español",
    "The password must contain:"                                         :   "La contraseña debe contener:",
    "USER DETAILS"                                                       :   "DETALLES DE USUARIO",
    "USER NAME"                                                          :   "USUARIO",
    "WebRT"                                                              :   "WebRT",
    "You have successfully changed your password!"                       :   "¡Has cambiado satisfactoriamente tu contraseña!",
    "You have successfully completed your registration!"                 :   "¡Has completado con éxito tu registro!",
    "Your password has expired and must be changed"                      :   "Su contraseña ha expirado y debe cambiarse",
    "Your password will expire in "                                      :   "Su contraseña expíra en ",
    " Days."                                                             :   " días.",
    "Complete the registration by filling the missing info:"             :   "Complete el registro llenando la siguiente información:",
    "PHONE NUMBER FOR AUTHENTICATION"                                    :   "NÚMERO DE TELÉFONO PARA AUTENTICACIÓN",
    "RE-ENTER NEW PASSWORD"                                              :   "re-ingrese nueva contraseña",
    "resend the verification code"                                       :   "reenviar el código de verificación",
    "Strength : "                                                        :   "fortaleza : ",
    "Must contain phone:"                                                :   "Debe contener número de teléfono:",
    "A well-formed phone number"                                         :   "Un número de teléfono bien formado",
    "Must contain email:"                                                :   "Debe contener correo electrónico:",
    "A well-formed email address"                                        :   "Una dirección de correo electrónico bien formada",
  };
export const LANG_HEB_NAME = 'heb';
export const LANG_HEB_TRANS = {
  "Example"                                                            :   "דוגמא",
  "must be a well-formed email address"                                :   "must be a well-formed email address",
  "Error: A registry process should be made!"                          :   "יש להשלים תהליך רישום",
  "Error: A registry process un valid!"                                :   "שם משתמש לא קיים",
  "VALIDATION_FAILED"                                                  :   "תהליך רישום לא תקין",
  "Bad credentials"                                                    :   "שם משתמש או סיסמא שגויים",
  "Password matches one of %1$s previous passwords."                   :   "בחר סיסמא חדשה שלא הייתה בשימוש",
  "Passwords do not match!"                                            :   "סיסמא שגויה",
  "Error: Email is already in use!"                                    :   'כתובת דוא"ל נמצאת בשימוש אצל משתמש קיים',
  "Error: Invalidate Pin-Code! User Not Approved"                      :   "קוד אימות שגוי",
  "Error: Unable to save your changes"                                 :   "לא ניתן לשמור את השינויים",
  "User account is locked"                                             :   "חשבונך ננעל",
  "Details Saved"                                                      :   "חשבונך ננעל",

  "% Days to expire"                                                   :   "בעוד % ימים יפוג תוקף הסיסמה",
  " A minimum of 8 characters"                                          :   "מינימום 8 ספרות",
  " At least 1 Uppercase letters"                                       :   "לפחות אות אחת גדולה",
  " At least 1 lowercase letters"                                       :   "לפחות אות אחת קטנה",
  " At least 1 special character"                                       :   "לפחות תו מיוחד אחד",
  " A number"                                                           :   "מספר",
  "APP CENTER"                                                         :   "APP CENTER",
  "Admin"                                                              :   "אדמיניסטרציה",
  "Aeonix App Center"                                                  :   "Aeonix App Center",
  "Agent"                                                              :   "נציג",
  "CHANGE PASSWORD"                                                    :   "שנה סיסמה",
  "Change Password"                                                    :   "שנה סיסמה",
  "Change Password and Login"                                          :   "שנה סיסמה והיכנס",
  "Change it now >"                                                    :   " <שנה עכשיו",
  "Change the Initial Password"                                        :   "שנה את הסיסמה הראשונית",
  "Chinese"                                                            :   "סינית",
  "Complete Registration"                                              :   "השלם תהליך רישום",
  "Continue"                                                           :   "המשך",
  "EMAIL"                                                              :   'כתובת דוא"ל',
  "Enable Profile Picture"                                             :   "אפשר תמונת פרופיל",
  "English"                                                            :   "אנגלית",
  "Ex. Saul Ramirez"                                                   :   "Ex. Saul Ramirez",
  "Ex: +972547762084"                                                  :   "Ex: +972547762084",
  "Ex: abc@example.com"                                                :   "Ex: abc@example.com",
  "FORGOT PASSWORD"                                                    :   "שכחתי סיסמה",
  "Forgot Password?"                                                   :   "שכחתי סיסמה",
  "Script-Designer"                                                    :   "Script Designer",
  "Hebrew"                                                             :   "עברית",
  "INITIAL PASSWORD"                                                   :   "סיסמה ראשונית",
  "LOGIN SCREEN"                                                       :   "מסך כניסה",
  "Log out"                                                            :   "יציאה",
  "Login"                                                              :   "כניסה",
  "My Account"                                                         :   "החשבון שלי",
  "NEW PASSWORD"                                                       :   "סיסמה חדשה",
  "OLD PASSWORD"                                                       :   "סיסמה ישנה",
  "PASSWORD"                                                           :   "סיסמה",
  "Please enter the Verification Code"                                 :   "אנא הקלד את קוד האימות",
  "you received in your mail:"                                         :   'שקיבלת בדוא"ל',
  "Please enter your User Name:"                                       :   "אנא הקלד את שם המשתמש שלך",
  "Send Verification Code again"                                       :   "שלח קוד אימות חדש",
  "REGISTRATION"                                                       :   "רישום",
  "Russian"                                                            :   "רוסית",
  "Send me a Verification Code"                                        :   "שלח לי קוד אימות",
  "Spanish"                                                            :   "ספרדית",
  "The password must contain:"                                         :   "על הסיסמה לכלול:",
  "USER DETAILS"                                                       :   "פרטי משתמש",
  "USER NAME"                                                          :   "שם משתמש",
  "WebRT"                                                              :   "דוחות זמן אמת",
  "You have successfully changed your password!"                       :   "סיסמתך שונתה בהצלחה",
  "You have successfully completed your registration!"                 :   "תהליך הרישום הסתיים בהצלחה",
  "Your password has expired and must be changed"                      :   "פג תוקף סיסמתך. עליך לשנותה",
  "Your password will expire in "                                      :   "תוקף סיסמתך יפוג בתוך ",
  " Days."                                                             :   " ימים",
  "Complete the registration by filling the missing info:"             :   "הקלד את המידע הבא לצורך השלמת תהליך הרישום",
  "PHONE NUMBER FOR AUTHENTICATION"                                    :   "מספר טלפון לאימות",
  "RE-ENTER NEW PASSWORD"                                              :   "הקלד שנית את הסיסמה שבחרת",
  "resend the verification code"                                       :   "שלח שוב קוד אימות",
  "Strength : "                                                        :   "חוזק : ",
  "Must contain phone:"                                                :   "חייב לכלול מספר טלפון",
  " A well-formed phone number"                                        :   "מספר טלפון תקני",
  "Must contain email:"                                                :   'חייב לכלול כתובת דוא"ל',
  " A well-formed email address"                                       :   'כתובת דוא"ל תקנית',
  "Settings"                                                          :   'הגדרות',

};
export const dictionary = {
  [LANG_ENG_NAME]: {dir: "ltr", trans: LANG_ENG_TRANS},
  [LANG_CHI_NAME]: {dir: "ltr", trans: LANG_CHI_TRANS},
  [LANG_ESP_NAME]: {dir: "ltr", trans: LANG_ESP_TRANS},
  [LANG_HEB_NAME]: {dir: "rtl", trans: LANG_HEB_TRANS},
};
export const TRANSLATION_PROVIDERS = [
  { provide: TRANSLATIONS, useValue: dictionary },
];

@Injectable({
  providedIn: 'root'
})
@Directive({
  selector: 'translate',
})
export class TranslateService {
  private _currentLang: string = 'eng';
  public get currentLang() {
    return this._currentLang;
  }

  public get currentDir() {
    return this._translations[this.currentLang].dir;
  }

  constructor(@Inject(TRANSLATIONS) private _translations: any) {
  }

  public use(lang: string): void {
    this._currentLang = lang;
  }
  public translate(key: string): string{
    if  (typeof(key) ==  undefined) {return "";}
    let translation = key;
    if (this._translations[this.currentLang] && this._translations[this.currentLang].trans[key]) {
      return this._translations[this.currentLang].trans[key];
    }
    return translation;
  }
  public instant(key: string) {
    return this.translate(key);
  }
}
